### ISSUE TITLE
New Installed packages were not saving in persistent volumes

### ISSUE THREAD

**Issue by kranthisai** [streamsets/datacollector-kubernetes#3]
Trying SDC as Kubernetes StatefulSets. When I try to download packages from package manager, the downloaded packages were not saving in persistent volume. When I restart the service, i dont see the new package installed.. 
I have set env variable STREAMSETS_LIBRARIES_EXTRA_DIR to /opt/streamsets-datacollector/streamsets-libs as that path is mounted. I can see newly installed packages, however, I dont see them in streamsets.

**Comment by kunickiaj** [comment]
`STREAMSETS_LIBRARIES_EXTRA_DIR` is *not* for stage libraries, it's for additional jars such as JDBC drivers that need to get loaded into a stage library's classloader. It inherently needs to be a different directory.

My recommendation is to build derived images as described here: https://github.com/streamsets/datacollector-docker#option-1---deriving-a-new-image-recommended

If, instead you still want to use PersistentVolumes and the Package Manager UI, you can define a volumeMount at the /opt/streamsets-datacollector/streamsets-libs path.

Be aware that Kubernetes handles volume mounts differently from Docker, and the directory will be *empty* on startup even those there are files at that path in the image. This means you will have no stage libraries installed (not even basic-lib) on the first start.

Let me know if this resolves the issue for you.

**Comment by kranthisai** [comment]
I build derived image.. It works.. I did do volumeMount at /opt/streamsets-datacollector/streamsets-libs path, I didnt get it working though.. So, I am using derived base image..
